### ISSUE TITLE
The projects os overall very awesome but the admin setting should have a login form and only admin can access through putting password there and add items not everyone 

### ISSUE THREAD

**Issue by RetroCaterpillar** [jnthnpstl/Arte2#10]

**Comment by jnthnpstl** [comment]
i planned doing that too but i got lazy and my instructor said it was okay not having admin account

**Comment by RetroCaterpillar** [comment]
I was looking for projects I'm a biology student fie to some turns i had to get admission in computer science now i have to submit a website which has admin setup with login to my instructor i decided to get help from github your project is very beautiful really love it of you can just add me the admin login and admin can sre how many orders have received I'll be very grateful

**Comment by jnthnpstl** [comment]
wish i could help but im very busy rn and i no longer intend to continue this project but you can

**Comment by RetroCaterpillar** [comment]
It's okay I've submitted this and Got fvcking A Grade All thanks to you and your wonderful project.
